package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Auction generated by hbm2java
 */
public class Auction  implements java.io.Serializable {


     private Integer id;
     private Card card;
     private User userByIdUserSeller;
     private User userByIdCurrentUser;
     private Date beginDate;
     private Date endDate;
     private String status;
     private String type;
     private BigDecimal currentAmount;
     private BigDecimal amount;
     private Set notifications = new HashSet(0);
     private Set reports = new HashSet(0);
     private Set orders = new HashSet(0);

    public Auction() {
    }

	
    public Auction(Card card, User userByIdUserSeller, Date beginDate, Date endDate, String status, String type) {
        this.card = card;
        this.userByIdUserSeller = userByIdUserSeller;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.status = status;
        this.type = type;
    }
    public Auction(Card card, User userByIdUserSeller, User userByIdCurrentUser, Date beginDate, Date endDate, String status, String type, BigDecimal currentAmount, BigDecimal amount, Set notifications, Set reports, Set orders) {
       this.card = card;
       this.userByIdUserSeller = userByIdUserSeller;
       this.userByIdCurrentUser = userByIdCurrentUser;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.status = status;
       this.type = type;
       this.currentAmount = currentAmount;
       this.amount = amount;
       this.notifications = notifications;
       this.reports = reports;
       this.orders = orders;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Card getCard() {
        return this.card;
    }
    
    public void setCard(Card card) {
        this.card = card;
    }
    public User getUserByIdUserSeller() {
        return this.userByIdUserSeller;
    }
    
    public void setUserByIdUserSeller(User userByIdUserSeller) {
        this.userByIdUserSeller = userByIdUserSeller;
    }
    public User getUserByIdCurrentUser() {
        return this.userByIdCurrentUser;
    }
    
    public void setUserByIdCurrentUser(User userByIdCurrentUser) {
        this.userByIdCurrentUser = userByIdCurrentUser;
    }
    public Date getBeginDate() {
        return this.beginDate;
    }
    
    public void setBeginDate(Date beginDate) {
        this.beginDate = beginDate;
    }
    public Date getEndDate() {
        return this.endDate;
    }
    
    public void setEndDate(Date endDate) {
        this.endDate = endDate;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getCurrentAmount() {
        return this.currentAmount;
    }
    
    public void setCurrentAmount(BigDecimal currentAmount) {
        this.currentAmount = currentAmount;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Set getNotifications() {
        return this.notifications;
    }
    
    public void setNotifications(Set notifications) {
        this.notifications = notifications;
    }
    public Set getReports() {
        return this.reports;
    }
    
    public void setReports(Set reports) {
        this.reports = reports;
    }
    public Set getOrders() {
        return this.orders;
    }
    
    public void setOrders(Set orders) {
        this.orders = orders;
    }




}


