package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import org.json.JSONException;
import org.json.JSONObject;

import java.math.BigDecimal;
import java.util.Date;
import java.util.Set;

/**
 * Auction generated by hbm2java
 */
public class Auction  implements java.io.Serializable {


     private Integer id;
     private Integer card;
     private Integer userByIdUserSeller;
     private String beginDate;
     private String endDate;
     private String status;
     private String type;
     private BigDecimal currentAmount;
     private BigDecimal amount;
     private Integer userByIdCurrentUser;

    public Auction() {
    }


    public Auction( Integer card,Integer userByIdUserSeller, String beginDate, String endDate, String status, String type) {
        this.setCard(card);
        this.userByIdUserSeller = userByIdUserSeller;
        this.beginDate = beginDate;
        this.endDate = endDate;
        this.status = status;
        this.type = type;
    }
    public Auction( Integer card,Integer userByIdUserSeller, Integer userByIdCurrentUser, String beginDate, String endDate, String status, String type, BigDecimal currentAmount, BigDecimal amount, Set notifications, Set reports, Set orders) {
        this.setCard(card);
       this.userByIdUserSeller = userByIdUserSeller;
       this.userByIdCurrentUser = userByIdCurrentUser;
       this.beginDate = beginDate;
       this.endDate = endDate;
       this.status = status;
       this.type = type;
       this.currentAmount = currentAmount;
       this.amount = amount;

    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getUserByIdUserSeller() {
        return this.userByIdUserSeller;
    }

    public void setUserByIdUserSeller(Integer userByIdUserSeller) {
        this.userByIdUserSeller = userByIdUserSeller;
    }
    public Integer getUserByIdCurrentUser() {
        return this.userByIdCurrentUser;
    }

    public void setUserByIdCurrentUser(Integer userByIdCurrentUser) {
        this.userByIdCurrentUser = userByIdCurrentUser;
    }
    public String getBeginDate() {
        return this.beginDate;
    }

    public void setBeginDate(String beginDate) {
        this.beginDate = beginDate;
    }
    public String getEndDate() {
        return this.endDate;
    }

    public void setEndDate(String endDate) {
        this.endDate = endDate;
    }
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }
    public BigDecimal getCurrentAmount() {
        return this.currentAmount;
    }

    public void setCurrentAmount(BigDecimal currentAmount) {
        this.currentAmount = currentAmount;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }

    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public String toJson(){
        String jsonText = null;

        JSONObject jsonObject = new JSONObject();
        try {
            jsonObject.put("id", getId());
            jsonObject.put("idCard", getCard());
            jsonObject.put("idUserSeller", getUserByIdUserSeller());
            jsonObject.put("currentAmount", getCurrentAmount());
            jsonObject.put("idCurrentUser",getUserByIdCurrentUser());
            jsonObject.put("beginDate", getBeginDate());
            jsonObject.put("endDate", getEndDate());
            jsonObject.put("status", getStatus());
            jsonObject.put("type", getType());
            jsonObject.put("amount", getAmount());

            jsonText = jsonObject.toString();
        } catch (JSONException e) {
            e.printStackTrace();
        }

        return jsonText;
    }


    public Integer getCard() {
        return card;
    }

    public void setCard(Integer card) {
        this.card = card;
    }
}


