package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Card generated by hbm2java
 */
public class Card  implements java.io.Serializable {


     private Integer id;
     private Category category;
     private Rarity rarity;
     private Supertype supertype;
     private String name;
     private String description;
     private BigDecimal cost;
     private BigDecimal minValue;
     private String status;
     private int manaCost;
     private Integer power;
     private Integer toughness;
     private boolean isFoil;
     private Set auctions = new HashSet(0);

    public Card() {
    }

	
    public Card(Category category, Rarity rarity, String name, String description, BigDecimal cost, BigDecimal minValue, String status, int manaCost, boolean isFoil) {
        this.category = category;
        this.rarity = rarity;
        this.name = name;
        this.description = description;
        this.cost = cost;
        this.minValue = minValue;
        this.status = status;
        this.manaCost = manaCost;
        this.isFoil = isFoil;
    }
    public Card(Category category, Rarity rarity, Supertype supertype, String name, String description, BigDecimal cost, BigDecimal minValue, String status, int manaCost, Integer power, Integer toughness, boolean isFoil, Set auctions) {
       this.category = category;
       this.rarity = rarity;
       this.supertype = supertype;
       this.name = name;
       this.description = description;
       this.cost = cost;
       this.minValue = minValue;
       this.status = status;
       this.manaCost = manaCost;
       this.power = power;
       this.toughness = toughness;
       this.isFoil = isFoil;
       this.auctions = auctions;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Rarity getRarity() {
        return this.rarity;
    }
    
    public void setRarity(Rarity rarity) {
        this.rarity = rarity;
    }
    public Supertype getSupertype() {
        return this.supertype;
    }
    
    public void setSupertype(Supertype supertype) {
        this.supertype = supertype;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public BigDecimal getCost() {
        return this.cost;
    }
    
    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }
    public BigDecimal getMinValue() {
        return this.minValue;
    }
    
    public void setMinValue(BigDecimal minValue) {
        this.minValue = minValue;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getManaCost() {
        return this.manaCost;
    }
    
    public void setManaCost(int manaCost) {
        this.manaCost = manaCost;
    }
    public Integer getPower() {
        return this.power;
    }
    
    public void setPower(Integer power) {
        this.power = power;
    }
    public Integer getToughness() {
        return this.toughness;
    }
    
    public void setToughness(Integer toughness) {
        this.toughness = toughness;
    }
    public boolean isIsFoil() {
        return this.isFoil;
    }
    
    public void setIsFoil(boolean isFoil) {
        this.isFoil = isFoil;
    }
    public Set getAuctions() {
        return this.auctions;
    }
    
    public void setAuctions(Set auctions) {
        this.auctions = auctions;
    }




}


