package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Profile generated by hbm2java
 */
public class Profile  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;
     private String type;
     private String status;
     private String email;
     private String phone;
     private String age;
     private String sex;
     private int coins;
     private BigDecimal rating;
     private String address;

    public Profile() {
    }

    public Profile(User user, String name, String type, String status, String email, String phone, String age, String sex, int coins, BigDecimal rating, String address) {
       this.user = user;
       this.name = name;
       this.type = type;
       this.status = status;
       this.email = email;
       this.phone = phone;
       this.age = age;
       this.sex = sex;
       this.coins = coins;
       this.rating = rating;
       this.address = address;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public int getCoins() {
        return this.coins;
    }
    
    public void setCoins(int coins) {
        this.coins = coins;
    }
    public BigDecimal getRating() {
        return this.rating;
    }
    
    public void setRating(BigDecimal rating) {
        this.rating = rating;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }




}


