package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * RAuctionCurrentusers generated by hbm2java
 */
public class RAuctionCurrentusers  implements java.io.Serializable {


     private Integer id;
     private int idCurrentUser;
     private BigDecimal amount;
     private Integer idAuction;

    public RAuctionCurrentusers() {
    }

	
    public RAuctionCurrentusers(int idCurrentUser, BigDecimal amount) {
        this.idCurrentUser = idCurrentUser;
        this.amount = amount;
    }
    public RAuctionCurrentusers(int idCurrentUser, BigDecimal amount, Integer idAuction) {
       this.idCurrentUser = idCurrentUser;
       this.amount = amount;
       this.idAuction = idAuction;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdCurrentUser() {
        return this.idCurrentUser;
    }
    
    public void setIdCurrentUser(int idCurrentUser) {
        this.idCurrentUser = idCurrentUser;
    }
    public BigDecimal getAmount() {
        return this.amount;
    }
    
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }
    public Integer getIdAuction() {
        return this.idAuction;
    }
    
    public void setIdAuction(Integer idAuction) {
        this.idAuction = idAuction;
    }




}


