package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1



/**
 * RCardMechanic generated by hbm2java
 */
public class RCardMechanic  implements java.io.Serializable {


     private Integer id;
     private int idCard;
     private int idMechanic;

    public RCardMechanic() {
    }

    public RCardMechanic(int idCard, int idMechanic) {
       this.idCard = idCard;
       this.idMechanic = idMechanic;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public int getIdCard() {
        return this.idCard;
    }
    
    public void setIdCard(int idCard) {
        this.idCard = idCard;
    }
    public int getIdMechanic() {
        return this.idMechanic;
    }
    
    public void setIdMechanic(int idMechanic) {
        this.idMechanic = idMechanic;
    }




}


