package com.example.xero.cardtradeapp.Entities;
// Generated May 12, 2018 6:06:40 PM by Hibernate Tools 4.3.1



/**
 * Report generated by hbm2java
 */
public class Report  implements java.io.Serializable {


     private Integer id;
     private Auction auction;
     private Reporttype reporttype;
     private String description;
     private String route;

    public Report() {
    }

    public Report(Auction auction, Reporttype reporttype, String description, String route) {
       this.auction = auction;
       this.reporttype = reporttype;
       this.description = description;
       this.route = route;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Auction getAuction() {
        return this.auction;
    }
    
    public void setAuction(Auction auction) {
        this.auction = auction;
    }
    public Reporttype getReporttype() {
        return this.reporttype;
    }
    
    public void setReporttype(Reporttype reporttype) {
        this.reporttype = reporttype;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getRoute() {
        return this.route;
    }
    
    public void setRoute(String route) {
        this.route = route;
    }




}


